import Replicate from "replicate";
import { PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import sharp from "sharp";

const WATERMARK_TEXT = "Generated by AI IIFJK";

function escapeXml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

async function addWatermark(buffer) {
  const image = sharp(buffer);
  const { width = 1024, height = 1024 } = await image.metadata();
  const barHeight = Math.max(48, Math.round(height * 0.07));
  const fontSize = Math.max(18, Math.round(barHeight * 0.4));

  const svg = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="${height - barHeight}" width="${width}" height="${barHeight}" fill="rgba(15,33,97,0.65)" />
      <text x="${width / 2}" y="${height - barHeight / 2}" text-anchor="middle" dominant-baseline="central"
        font-family="Arial, Helvetica, sans-serif" font-size="${fontSize}" font-weight="700"
        fill="#ffffff" letter-spacing="1">${escapeXml(WATERMARK_TEXT)}</text>
    </svg>`;

  return image
    .composite([{ input: Buffer.from(svg), top: 0, left: 0 }])
    .toFormat("webp", { quality: 95 })
    .toBuffer();
}

export async function POST(request) {
  const { image, prompt, style = "Classic" } = await request.json();

  if (!Array.isArray(image) || image.length === 0) {
    return Response.json({ error: "At least one image URL is required." }, { status: 400 });
  }
  if (!process.env.REPLICATE_API_TOKEN) {
    return Response.json({ error: "REPLICATE_API_TOKEN is not configured." }, { status: 503 });
  }

  try {
    const replicate = new Replicate({ auth: process.env.REPLICATE_API_TOKEN });
    const output = await replicate.run("qwen/qwen-image-edit-2511", {
      input: {
        image,
        prompt: prompt || `Create a ${style.toLowerCase()} festival caricature from these photos.`,
        go_fast: true,
        lora_scale: 1,
        aspect_ratio: "3:4",
        lora_weights: "",
        output_format: "webp",
        output_quality: 95,
      },
    });
    const outputUrl = output?.[0]?.url?.() || output?.[0];
    if (!outputUrl) {
      return Response.json({ error: "The model did not return an image." }, { status: 502 });
    }

    const generatedResponse = await fetch(outputUrl);
    const rawBuffer = Buffer.from(await generatedResponse.arrayBuffer());
    const watermarkedBuffer = await addWatermark(rawBuffer);

    let storedUrl;
    if (process.env.VITE_S3_BUCKET && process.env.VITE_AWS_REGION) {
      const key = `caricatures/${crypto.randomUUID()}.webp`;
      const s3 = new S3Client({
        region: process.env.VITE_AWS_REGION,
        credentials: {
          accessKeyId: process.env.VITE_AWS_ACCESS_KEY,
          secretAccessKey: process.env.VITE_AWS_SECRET_KEY,
        },
      });
      await s3.send(
        new PutObjectCommand({
          Bucket: process.env.VITE_S3_BUCKET,
          Key: key,
          Body: watermarkedBuffer,
          ContentType: "image/webp",
        })
      );
      storedUrl = process.env.VITE_S3_PUBLIC_BASE_URL
        ? `${process.env.VITE_S3_PUBLIC_BASE_URL}/${key}`
        : `https://${process.env.VITE_S3_BUCKET}.s3.${process.env.VITE_AWS_REGION}.amazonaws.com/${key}`;
    } else {
      storedUrl = `data:image/webp;base64,${watermarkedBuffer.toString("base64")}`;
    }

    return Response.json({ url: storedUrl });
  } catch (error) {
    return Response.json({ error: error.message || "Generation failed." }, { status: 500 });
  }
}
